name: Build and Deploy

on: push

jobs:
  build:
    name: Build Hugo site
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Hugo
        run: |
         sudo apt-get update
         sudo apt-get install -y hugo

      - name: Build Hugo Command
        run: hugo
