name: Build and Deploy

on: push

jobs:
  build:
    name: Build Hugo site
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.68.1'

      - name: Build
        run: hugo
